project:
  type: website

website:
  title: "Andrés Rodríguez-Clare"
  site-url: https://andres.econ.berkeley.edu

format:
  html:
    theme: 
      - cosmo
    css: styles.css
    toc: false
    anchor-sections: false
    include-in-header: header.html
