project:
  type: website

website:
  title: "Andrés Rodríguez-Clare"
  site-url: https://andres.econ.berkeley.edu

format:
  html:
    theme: 
      - cosmo
    css: styles.css
    toc: false
    anchor-sections: false
    include-in-header: |
      <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">
